// ignore_for_file: constant_identifier_names

enum AppErrorCode {
// Group errors
  GROUP_NOT_FOUND,
  GROUP_DETAILS_UNCHANGED,

  // Task errors
  TASK_NOT_FOUND,

  // Access / permission errors
  ACCESS_DENIED,
  OWNER_CANNOT_PERFORM_ACTION,
  SHARED_USER_CANNOT_PERFORM_ACTION,

  // User errors
  USER_NOT_FOUND,
  USER_ALREADY_VERIFIED,
  USER_NOT_ASSIGNED_TO_TASK,
  INVALID_URL,

  // Auth errors
  INVALID_CREDENTIALS,
  EMAIL_ALREADY_IN_USE,
  USERNAME_ALREADY_IN_USE,
  CREDENTIALS_ALREADY_IN_USE,
  INVALID_TOKEN, // covers invalid/expired refresh, verification, and password reset tokens
  INVALID_GOOGLE_TOKEN, // Google JWT validation failure

  // Member management errors
  USER_ALREADY_GRANTED,
  USER_ALREADY_REVOKED,
  NO_USERNAMES_PROVIDED,

  // Server errors
  INTERNAL_ERROR,
  EMAIL_SEND_FAILED,

  // Client error
  UNKNOWN,

  NO_FILE_PICKED,
  SESSION_EXPIRED,
  OFFLINE_ACCESS_DENIED,

  // Dio / network errors
  DIO_CONNECTION_TIMEOUT,
  DIO_SEND_TIMEOUT,
  DIO_RECEIVE_TIMEOUT,
  DIO_BAD_CERTIFICATE,
  DIO_REQUEST_CANCELLED,
  DIO_CONNECTION_ERROR,

  // HTTP client errors (4xx)
  HTTP_BAD_REQUEST, // 400
  HTTP_UNAUTHORIZED, // 401
  HTTP_FORBIDDEN, // 403
  HTTP_NOT_FOUND, // 404
  HTTP_REQUEST_TIMEOUT, // 408
  HTTP_UNPROCESSABLE, // 422
  HTTP_TOO_MANY_REQUESTS, // 429
  HTTP_UNEXPECTED, // fallback for unmapped codes
}
